add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"
command_timeout = 3600000
scan_timeout = 500

format = """
[░▒▓](#7fb6c8)\
$os\
[](bg:#2e303e fg:#7fb6c8)\
$username\
$hostname\
[](bg:#4e586c fg:#2e303e)\
$directory\
[](fg:#4e586c bg:#0b8e92)\
$git_branch\
$git_status\
[](fg:#0b8e92 bg:#2d6180)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$lua\
$perl\
$php\
$python\
$ruby\
$swift\
$docker_context\
[ ](fg:#2d6180)\
$fill\
[ ](fg:#0b8e92)\
$cmd_duration\
[ ](fg:#7fb6c8 bg:#0b8e92)\
$time\
[▓▒░](#7fb6c8)\n\
$character\
"""

[fill]
symbol = '─'

[character]
success_symbol = '[▸▹](bold #0b8e92)'
error_symbol = '[▸▹](bold #ff5555)'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#2e303e fg:#fafaf4"
style_root = "bg:#2e303e fg:#fafaf4"
format = '[ $user](bold $style)'
disabled = false

[hostname]
style = "bg:#2e303e fg:#fafaf4"
ssh_only = false
format = '[@$hostname ](bold $style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#7fb6c8 fg:#181a21"
format = "[  ](bold $style)"
disabled = false # Disabled by default

[directory]
style = "bg:#4e586c fg:#fafaf4"
read_only_style = "bg:#4e586c fg:#ff5555"
read_only = ""
format = "[  $path ]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = ""
"Sources" = "󰈮"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#0b8e92 fg:#fafaf4"
format = '[ $symbol $branch]($style)'

[git_status]
ignore_submodules = true
style = "bg:#0b8e92 fg:#fafaf4"
format = '[ $all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[perl]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = " "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = "ﯣ "
style = "bg:#2d6180 fg:#fafaf4"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#7fb6c8 fg:#181a21"
format = '[ $time ](bold $style)'

[cmd_duration]
min_time = 0
style = "bg:#0b8e92 fg:#fafaf4"
format = "[ ◄ $duration](italic $style)"
