#!/usr/bin/env bash

find . -type d -exec chmod 755 {} +
find . -type f -exec chmod 644 {} +
find . -type d -exec chmod 755 {} +
find . -type f -name "*.exe" -exec chmod +x {} +
find . -type f -name "*.sh" -exec chmod +x {} +
