#!/usr/bin/env bash

[[ -z "$1" ]] && echo "Sintaks: mirror JUMLAH UMUR NEGARA, contoh: mirror 10 10 id,sg" && exit 1

JUMLAH="$1"
UMUR="$2"
NEGARA="$3"

echo ""
echo "Jumlah    : $JUMLAH"
echo "Umur      : $UMUR"
echo "Negara    : $NEGARA"
echo ""

sudo reflector --verbose --sort rate -n "$JUMLAH" -a "$UMUR" -c "$NEGARA" -p https --ipv4 --verbose --save /etc/pacman.d/mirrorlist

sudo sed -i '11i CacheServer = http:\/\/192.168.8.2\/arch\n' /etc/pacman.d/mirrorlist

echo ""

cat /etc/pacman.d/mirrorlist
