#!/usr/bin/env bash

LC_NUMERIC="en_GB.UTF-8"

# Read Motherboard Temperatures
HWMON_PATH=$(grep -l 'nct6687*' /sys/class/hwmon/hwmon*/name)

if [ -n "$HWMON_PATH" ]; then
    MOBO=$(< "${HWMON_PATH%/name}/temp2_input")
    VRM=$(< "${HWMON_PATH%/name}/temp3_input")
    PCH=$(< "${HWMON_PATH%/name}/temp5_input")
    RADIATOR=$(< "${HWMON_PATH%/name}/fan1_input")
    TOP_FANS=$(< "${HWMON_PATH%/name}/fan4_input")
    BOTTOM1_FANS=$(< "${HWMON_PATH%/name}/fan5_input")
    BOTTOM2_FANS=$(< "${HWMON_PATH%/name}/fan6_input")

    MOBO=$((MOBO / 1000))
    VRM=$((VRM / 1000))
    PCH=$((PCH / 1000))
else
    echo "nct6687 sensor module not found!"

    exit 1
fi

# Read CPU Temperatures
HWMON_PATH=$(grep -l 'k10temp' /sys/class/hwmon/hwmon*/name)

if [ -n "$HWMON_PATH" ]; then
    CPU_TCTL=$(< "${HWMON_PATH%/name}/temp1_input")
    CPU_TCCD=$(< "${HWMON_PATH%/name}/temp3_input")

    CPU_TCTL=$((CPU_TCTL / 1000))
    CPU_TCCD=$((CPU_TCCD / 1000))

    CPU_POWER=$(/usr/local/bin/ryzen)
else
    echo "k10temp sensor module not found!"

    exit 1
fi

# Read GPU Temperatures
HWMON_PATH=$(grep -l 'amdgpu' /sys/class/hwmon/hwmon*/name)

if [ -n "$HWMON_PATH" ]; then
    GPU_EDGE=$(< "${HWMON_PATH%/name}/temp1_input")
    GPU_JUNCTION=$(< "${HWMON_PATH%/name}/temp2_input")
    GPU_MEM=$(< "${HWMON_PATH%/name}/temp3_input")
    GPU_POWER=$(< "${HWMON_PATH%/name}/power1_average")

    GPU_EDGE=$((GPU_EDGE / 1000))
    GPU_JUNCTION=$((GPU_JUNCTION / 1000))
    GPU_MEM=$((GPU_MEM / 1000))
    GPU_POWER=$((GPU_POWER / 1000 / 1000))
else
    echo "amdgpu sensor module not found!"

    exit 1
fi

# Read NVMe Temperatures
NVME1=$(< /sys/class/hwmon/hwmon5/temp1_input)
NVME2=$(< /sys/class/hwmon/hwmon3/temp1_input)
NVME3=$(< /sys/class/hwmon/hwmon2/temp1_input)
NVME4=$(< /sys/class/hwmon/hwmon4/temp1_input)

NVME1=$((NVME1 / 1000))
NVME2=$((NVME2 / 1000))
NVME3=$((NVME3 / 1000))
NVME4=$((NVME4 / 1000))

# Output Data
echo ""
echo "ASRock B650E Steel Legend"
printf "Mobo     : %.2f°C\n" "$MOBO"
printf "VRM      : %.2f°C\n" "$VRM"
printf "Chipset  : %.2f°C\n" "$PCH"
echo ""

echo "AMD Ryzen 7 7800X3D"
printf "Tctl     : %.2f°C\n" "$CPU_TCTL"
printf "Tccd     : %.2f°C\n" "$CPU_TCCD"
printf "Power    : %.2f W\n" "$CPU_POWER"
echo ""

echo "AMD Radeon RX 6800 XT"
printf "Edge     : %.2f°C\n" "$GPU_EDGE"
printf "Junction : %.2f°C\n" "$GPU_JUNCTION"
printf "Mem      : %.2f°C\n" "$GPU_MEM"
printf "Power    : %.2f W\n" "$GPU_POWER"
echo ""

echo "PNY CS3030 2TB"
printf "NAND     : %.2f°C\n" "$NVME1"
echo ""

echo "AddLink S70 2TB"
printf "NAND     : %.2f°C\n" "$NVME2"
echo ""

echo "AddLink S70 2TB"
printf "NAND     : %.2f°C\n" "$NVME3"
echo ""

echo "Transcend TS1TMTE220S 1TB"
printf "NAND     : %.2f°C\n" "$NVME4"
echo ""

echo "Lian Li Lancool II"
printf "Radiator : %d RPM\n" "$RADIATOR"
printf "Top      : %d RPM\n" "$TOP_FANS"
printf "Bottom 1 : %d RPM\n" "$BOTTOM1_FANS"
printf "Bottom 2 : %d RPM\n" "$BOTTOM2_FANS"
